version: "3"

services:
  api:
    container_name: api
    build:
      context: ./
    ports:
      - 8080:8080
    #    links:
    #      - db
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/github.com/NUTFes/shift-app
#    environment:
#      GO111MODULE: "on"
#  db:
#    container_name: db
#    image: mysql:8.0.15
#    build: ./mysql/
#    hostname: mysql
#    ports:
#      - "3306:3306"
#    env_file:
#      - ./mysql/env
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
#    volumes:
#      - "./mysql_data/mysql:/car/lib/mysql"
#      - "./mysql/my.conf:/etc/mysql/my.conf"
#      - "./mysql/init/:/docker-entrypoint-initdb.d"
