version: "3"

services:
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - 3000:3000
    links:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./api:/go/src/github.com/NUTFes/shift-app
    environment:
      GO111MODULE: "on"
      http_proxy: "http://proxy.nagaokaut.ac.jp:8080"
      https_proxy: "http://proxy.nagaokaut.ac.jp:8080"
    env_file: .env

  db:
    container_name: db
    build:
      context: ./mysql
    hostname: mysql
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "./mysql_data/mysql:/car/lib/mysql"
      - "./mysql/init/:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pwd

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    links:
      - db
    ports:
      - "8080:8080"
